// pages/Diff.vue
<template>
  <div class="flex flex-col h-[calc(100vh-8rem)]">
    <div class="mb-4 flex items-center justify-between px-2 shrink-0">
      <div class="flex items-center gap-4">
        <el-button circle @click="router.back()">
          <ArrowLeft class="w-5 h-5" />
        </el-button>
        <div>
          <h1 class="text-xl font-bold text-gray-800 flex items-center gap-3">
            版本对比
            <div v-if="diffData" class="flex items-center gap-1 text-sm font-medium bg-gray-100 px-4 py-1.5 rounded-full text-gray-500 italic">
              {{ diffData.v2_summary }} <span class="mx-1">→</span> <span class="text-blue-600 truncate max-w-[300px]">{{ diffData.v1_summary }}</span>
            </div>
          </h1>
        </div>
      </div>
      <el-button type="danger" plain @click="handleRollback">
        <RotateCcw class="w-4 h-4 mr-1" /> 回滚至该历史版本
      </el-button>
    </div>

    <div class="flex-1 bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden flex flex-col">
      <div class="grid grid-cols-2 bg-gray-50 border-b border-gray-200 text-sm font-bold text-gray-500">
          <div class="p-3 pl-14 border-r border-gray-200">历史选定版本 (ID: {{ v2 }})</div>
          <div class="p-3 pl-14">当前对比版本 (ID: {{ v1 }})</div>
      </div>
      <div class="flex-1 relative">
        <div ref="diffContainer" class="w-full h-full"></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import * as monaco from 'monaco-editor';
import { ArrowLeft, RotateCcw } from 'lucide-vue-next';
import { ElMessageBox, ElMessage } from 'element-plus';
import { api } from '@/services/api';
import type { DiffResponse } from '@/types';

const route = useRoute();
const router = useRouter();
const id = computed(() => route.params.id as string);
const v1 = computed(() => route.params.v1 as string);
const v2 = computed(() => route.params.v2 as string);

const diffContainer = ref<HTMLElement | null>(null);
let diffEditor: monaco.editor.IStandaloneDiffEditor | null = null;
const diffData = ref<DiffResponse | null>(null);

const loadDiff = async () => {
  if (v1.value && v2.value) {
    try {
      const data = await api.getDiff(v1.value, v2.value);
      diffData.value = data;
      if (diffEditor) {
        const originalModel = monaco.editor.createModel(data.content_v2, 'sql');
        const modifiedModel = monaco.editor.createModel(data.content_v1, 'sql');
        diffEditor.setModel({
          original: originalModel,
          modified: modifiedModel
        });
      }
    } catch (err) {
      console.error("对比加载失败", err);
      ElMessage.error('对比加载失败');
    }
  }
};

onMounted(() => {
  if (diffContainer.value) {
    diffEditor = monaco.editor.createDiffEditor(diffContainer.value, {
      theme: 'vs',
      automaticLayout: true,
      originalEditable: false,
      readOnly: true,
      fontSize: 14,
      minimap: { enabled: false },
      scrollBeyondLastLine: false,
    });
    loadDiff();
  }
});

onBeforeUnmount(() => {
  if (diffEditor) diffEditor.dispose();
});

const handleRollback = () => {
  if (!id.value || !v2.value) return;
  
  ElMessageBox.confirm(
    `确定要回滚到历史版本 (ID:${v2.value}) 吗？`,
    '回滚确认',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(async () => {
    try {
      const res = await api.rollbackProcedure(parseInt(id.value), parseInt(v2.value));
      if (res.flag) {
        ElMessage.success(res.message);
        router.push(`/editor/${id.value}`);
      }
    } catch (err) {
      ElMessage.error("回滚失败");
    }
  }).catch(() => {});
};
</script>

<style scoped>
:deep(.monaco-diff-editor) {
  padding-top: 8px;
}
</style>

// pages/Diff.tsx

import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, RotateCcw, RotateCw } from 'lucide-react';
import { DiffEditor, loader } from '@monaco-editor/react';
import { api } from '../services/api';
import { DiffResponse } from '../types';

loader.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs' } });

const Diff: React.FC = () => {
  const { id, v1, v2 } = useParams<{ id: string; v1: string; v2: string }>();
  const navigate = useNavigate();
  const [diffData, setDiffData] = useState<DiffResponse | null>(null);

  useEffect(() => {
    if (v1 && v2) {
      api.getDiff(v1, v2).then(setDiffData).catch(err => console.error("对比加载失败", err));
    }
  }, [v1, v2]);

  const handleRollback = async () => {
    if (!id || !v2) return;
    if (confirm(`确定要回滚到历史版本 (ID:${v2}) 吗？`)) {
        try {
          const res = await api.rollbackProcedure(parseInt(id), parseInt(v2));
          if (res.flag) {
            alert(res.message);
            navigate(`/editor/${id}`);
          }
        } catch (err) {
          alert("回滚失败");
        }
    }
  };

  if (!diffData) return <div className="p-10 text-center">加载对比中...</div>;

  return (
    <div className="flex flex-col h-[calc(100vh-8rem)]">
      <div className="mb-4 flex items-center justify-between px-2 shrink-0">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-2 hover:bg-white rounded-full transition-colors text-gray-500 hover:text-gray-800"><ArrowLeft className="w-5 h-5" /></button>
          <div>
            <h1 className="text-xl font-bold text-gray-800 flex items-center gap-3">
              版本对比
              <div className="flex items-center gap-1 text-xs font-normal bg-gray-100 px-3 py-1 rounded-full text-gray-500 italic">
                {diffData.v2_summary} <span className="mx-1">→</span> <span className="text-blue-600">{diffData.v1_summary}</span>
              </div>
            </h1>
          </div>
        </div>
        <button onClick={handleRollback} className="flex items-center gap-2 bg-white border border-red-200 text-red-600 hover:bg-red-50 px-4 py-2 rounded-lg text-sm font-medium shadow-sm transition-colors">
            <RotateCcw className="w-4 h-4" /> 回滚至该历史版本
        </button>
      </div>

      <div className="flex-1 bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden flex flex-col">
        <div className="grid grid-cols-2 bg-gray-50 border-b border-gray-200 text-xs text-gray-500 font-mono">
            <div className="p-2 pl-14 border-r border-gray-200">历史选定版本 (ID: {v2})</div>
            <div className="p-2 pl-14">当前对比版本 (ID: {v1})</div>
        </div>
        <div className="flex-1 relative">
            <DiffEditor
                height="100%"
                language="sql"
                original={diffData.content_v2}
                modified={diffData.content_v1}
                theme="light"
                options={{ originalEditable: false, readOnly: true, fontSize: 13, automaticLayout: true, minimap: { enabled: false } }}
            />
        </div>
      </div>
    </div>
  );
};

export default Diff;
